[tool.poetry]
name = "coolors"
version = "0.1.3"
description = "generates 5 random colors by scraping coolors.co"
authors = ["Arjun Gandhi <account@arjugandhi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pyppeteer = "^0.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
