[project]
dependencies = []
description = "The elegance of Airflow + the power of AWS"
dynamic = [ "classifiers",]
keywords = [ "orchestration", "aws", "cloud",]
name = "orkestra"
requires-python = ">=3.8"
version = "0.9.4"
readme = "README.md"
[[project.authors]]
name = "Stephan Fitzpatrick"
email = "knowsuchagency@gmail.com"

[build-system]
build-backend = "pdm.pep517.api"
requires = [ "pdm-pep517",]

[project.license]
text = "MIT"

[project.urls]
Repository = "https://github.com/knowsuchagency/orkestra"
homepage = "https://github.com/knowsuchagency/orkestra"
Documentation = "https://knowsuchagency.github.io/orkestra/"

[project.optional-dependencies]
cdk = [ "aws-cdk.core", "aws-cdk.aws_events", "aws-cdk.aws_events_targets", "aws-cdk.aws_lambda_python", "aws-cdk.aws_stepfunctions_tasks",]
powertools = [ "aws-lambda-powertools[pydantic]", "pydantic[email]",]

[tool.isort]
profile = "black"

[tool.black]
line-length = 79
include = "\\.pyi?$"
exclude = "/(\n    \\.git\n  | \\.hg\n  | \\.mypy_cache\n  | \\.tox\n  | \\.venv\n  | \\.history\n  | _build\n  | buck-out\n  | build\n  | dist\n  | __pypackages__\n  | cdk.out\n)/\n"

[tool.pdm.dev-dependencies]
dev = [ "klaxon", "mkdocs-material", "pre-commit", "black", "aws-cdk.aws_apigateway", "mangum", "fastapi", "uvicorn", "boto3", "twine", "mkdocstrings", "aws-cdk.aws_batch", "aws-cdk.pipelines", "aws-cdk.aws_s3_deployment",]
test = [ "pytest", "coverage", "pytest-cov", "hypothesis", "boto3",]

[tool.pdm.scripts]
format = "black ./"
synth = "cdk synth"
shell = "pdm run coverage run -m pytest tests/unit/\ncoverage html\nopen htmlcov/index.html\n"
test-pypi = "twine upload --repository testpypi dist/*"
pypi = "twine upload dist/*"
docs = "mkdocs serve"
unit-tests = "pytest tests/unit/"
integration-tests = "pytest tests/integration/"
api = "uvicorn examples.rest:app --reload"
install-hooks = "pre-commit install --install-hooks"
clean = "find . -iname '*.pyc' -delete"

[tool.pytest.ini_options]
testpaths = [ "tests",]
markers = [ "slow", "cdk", "powertools",]

[tool.coverage.run]
source = [ "orkestra",]

[tool.pdm.scripts._]
env_file = ".env"

[tool.pdm.scripts.deploy]

[tool.pdm.scripts.destroy]

[tool.pdm.scripts.publish]

[tool.pdm.scripts.coverage-report]
