[tool.poetry]
name = "kapla-cli"
version = "3.3.0"
description = ""
authors = ["Guillaume Charbonnier <guillaume.charbonnier@araymond.com>"]
packages = [{ include="kapla" }]

[tool.poetry.dependencies]
python = "^3.8"
kapla-cli-core = "^3.3.0"
colorama = "^0.4.4"
commitizen = "^2.17.9"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
black = "^21.6b0"
flake8 = "^3.9.2"
isort = "^5.8.0"
mypy = "^0.902"
pre-commit = "^2.13.0"
twine = "^3.4.1"
snakeviz = "^2.1.0"

[tool.poetry.dev-dependencies]
kapla-cli-core = { path="../core/" }

[tool.poetry.scripts]
k = "kapla.cli.app:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
